version: '3'
services:
  db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
    networks:
      - factset-networks
  factset-api:
    build: .
    volumes:
        - .:/app
        - /app/node_modules
    container_name: factset-api
    ports:
      - 49161:3000
    networks:
      - factset-networks
    environment:
      PORT: 3000
      MONGO_URL: mongodb://db:27017
      MONGO_DBNAME: factset
    depends_on:
      - db
volumes:
  db:
networks:
  factset-networks: 
    driver: bridge